### ISSUE TITLE
Stephen Katuli - Morning session: peer-to-peer code reviews

### ISSUE THREAD

**Issue by Amen-Musingarimi** [stephenkati/Portfolio-setup-and-mobile-first#9]
We reviewed Stephen's code and we all agreed that it looks good 
However, in the **header** element, we noticed that two **nav** tags were used, we all suggested that using one **nav** tag would improve the readability of the code. In addition, in the stylesheet, the **flex-direction** is defined as **row**, which is not really necessary as the default **flex-direction** is **row**.

**Comment by stephenkati** [comment]
Issues fixed
